//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("freddacaixaModel", "fk_Foto_Galeria", "galeria", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ModuloBasico.Galeria), "foto", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ModuloBasico.Foto))]

// Original file name:
// Generation date: 22/8/2010 20:46:11
namespace ModuloBasico
{
    
    /// <summary>
    /// There are no comments for FredDaCaixaEntities in the schema.
    /// </summary>
    public partial class FredDaCaixaEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new FredDaCaixaEntities object using the connection string found in the 'FredDaCaixaEntities' section of the application configuration file.
        /// </summary>
        public FredDaCaixaEntities() : 
                base("name=FredDaCaixaEntities", "FredDaCaixaEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new FredDaCaixaEntities object.
        /// </summary>
        public FredDaCaixaEntities(string connectionString) : 
                base(connectionString, "FredDaCaixaEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new FredDaCaixaEntities object.
        /// </summary>
        public FredDaCaixaEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "FredDaCaixaEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for FotoSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Foto> FotoSet
        {
            get
            {
                if ((this._FotoSet == null))
                {
                    this._FotoSet = base.CreateQuery<Foto>("[FotoSet]");
                }
                return this._FotoSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Foto> _FotoSet;
        /// <summary>
        /// There are no comments for GaleriaSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Galeria> GaleriaSet
        {
            get
            {
                if ((this._GaleriaSet == null))
                {
                    this._GaleriaSet = base.CreateQuery<Galeria>("[GaleriaSet]");
                }
                return this._GaleriaSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Galeria> _GaleriaSet;
        /// <summary>
        /// There are no comments for IndexSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Index> IndexSet
        {
            get
            {
                if ((this._IndexSet == null))
                {
                    this._IndexSet = base.CreateQuery<Index>("[IndexSet]");
                }
                return this._IndexSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Index> _IndexSet;
        /// <summary>
        /// There are no comments for PropostaSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Proposta> PropostaSet
        {
            get
            {
                if ((this._PropostaSet == null))
                {
                    this._PropostaSet = base.CreateQuery<Proposta>("[PropostaSet]");
                }
                return this._PropostaSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Proposta> _PropostaSet;
        /// <summary>
        /// There are no comments for UsuarioSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Usuario> UsuarioSet
        {
            get
            {
                if ((this._UsuarioSet == null))
                {
                    this._UsuarioSet = base.CreateQuery<Usuario>("[UsuarioSet]");
                }
                return this._UsuarioSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Usuario> _UsuarioSet;
        /// <summary>
        /// There are no comments for FotoSet in the schema.
        /// </summary>
        public void AddToFotoSet(Foto foto)
        {
            base.AddObject("FotoSet", foto);
        }
        /// <summary>
        /// There are no comments for GaleriaSet in the schema.
        /// </summary>
        public void AddToGaleriaSet(Galeria galeria)
        {
            base.AddObject("GaleriaSet", galeria);
        }
        /// <summary>
        /// There are no comments for IndexSet in the schema.
        /// </summary>
        public void AddToIndexSet(Index index)
        {
            base.AddObject("IndexSet", index);
        }
        /// <summary>
        /// There are no comments for PropostaSet in the schema.
        /// </summary>
        public void AddToPropostaSet(Proposta proposta)
        {
            base.AddObject("PropostaSet", proposta);
        }
        /// <summary>
        /// There are no comments for UsuarioSet in the schema.
        /// </summary>
        public void AddToUsuarioSet(Usuario usuario)
        {
            base.AddObject("UsuarioSet", usuario);
        }
    }
    /// <summary>
    /// There are no comments for freddacaixaModel.Foto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="freddacaixaModel", Name="Foto")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Foto : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Foto object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static Foto CreateFoto(int id)
        {
            Foto foto = new Foto();
            foto.ID = id;
            return foto;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property ImagemUrl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagemUrl
        {
            get
            {
                return this._ImagemUrl;
            }
            set
            {
                this.OnImagemUrlChanging(value);
                this.ReportPropertyChanging("ImagemUrl");
                this._ImagemUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ImagemUrl");
                this.OnImagemUrlChanged();
            }
        }
        private string _ImagemUrl;
        partial void OnImagemUrlChanging(string value);
        partial void OnImagemUrlChanged();
        /// <summary>
        /// There are no comments for Property Legenda in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Legenda
        {
            get
            {
                return this._Legenda;
            }
            set
            {
                this.OnLegendaChanging(value);
                this.ReportPropertyChanging("Legenda");
                this._Legenda = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Legenda");
                this.OnLegendaChanged();
            }
        }
        private string _Legenda;
        partial void OnLegendaChanging(string value);
        partial void OnLegendaChanged();
        /// <summary>
        /// There are no comments for Property Titulo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo
        {
            get
            {
                return this._Titulo;
            }
            set
            {
                this.OnTituloChanging(value);
                this.ReportPropertyChanging("Titulo");
                this._Titulo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Titulo");
                this.OnTituloChanged();
            }
        }
        private string _Titulo;
        partial void OnTituloChanging(string value);
        partial void OnTituloChanged();
        /// <summary>
        /// There are no comments for galeria in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("freddacaixaModel", "fk_Foto_Galeria", "galeria")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Galeria galeria
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Galeria>("freddacaixaModel.fk_Foto_Galeria", "galeria").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Galeria>("freddacaixaModel.fk_Foto_Galeria", "galeria").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for galeria in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Galeria> galeriaReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Galeria>("freddacaixaModel.fk_Foto_Galeria", "galeria");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Galeria>("freddacaixaModel.fk_Foto_Galeria", "galeria", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for freddacaixaModel.Galeria in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="freddacaixaModel", Name="Galeria")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Galeria : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Galeria object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static Galeria CreateGaleria(int id)
        {
            Galeria galeria = new Galeria();
            galeria.ID = id;
            return galeria;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property ImagemUrl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagemUrl
        {
            get
            {
                return this._ImagemUrl;
            }
            set
            {
                this.OnImagemUrlChanging(value);
                this.ReportPropertyChanging("ImagemUrl");
                this._ImagemUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ImagemUrl");
                this.OnImagemUrlChanged();
            }
        }
        private string _ImagemUrl;
        partial void OnImagemUrlChanging(string value);
        partial void OnImagemUrlChanged();
        /// <summary>
        /// There are no comments for Property Legenda in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Legenda
        {
            get
            {
                return this._Legenda;
            }
            set
            {
                this.OnLegendaChanging(value);
                this.ReportPropertyChanging("Legenda");
                this._Legenda = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Legenda");
                this.OnLegendaChanged();
            }
        }
        private string _Legenda;
        partial void OnLegendaChanging(string value);
        partial void OnLegendaChanged();
        /// <summary>
        /// There are no comments for Property Titulo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo
        {
            get
            {
                return this._Titulo;
            }
            set
            {
                this.OnTituloChanging(value);
                this.ReportPropertyChanging("Titulo");
                this._Titulo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Titulo");
                this.OnTituloChanged();
            }
        }
        private string _Titulo;
        partial void OnTituloChanging(string value);
        partial void OnTituloChanged();
        /// <summary>
        /// There are no comments for foto in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("freddacaixaModel", "fk_Foto_Galeria", "foto")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Foto> foto
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Foto>("freddacaixaModel.fk_Foto_Galeria", "foto");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Foto>("freddacaixaModel.fk_Foto_Galeria", "foto", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for freddacaixaModel.Index in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="freddacaixaModel", Name="Index")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Index : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Index object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static Index CreateIndex(int id)
        {
            Index index = new Index();
            index.ID = id;
            return index;
        }
        /// <summary>
        /// There are no comments for Property Corpo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Corpo
        {
            get
            {
                return this._Corpo;
            }
            set
            {
                this.OnCorpoChanging(value);
                this.ReportPropertyChanging("Corpo");
                this._Corpo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Corpo");
                this.OnCorpoChanged();
            }
        }
        private string _Corpo;
        partial void OnCorpoChanging(string value);
        partial void OnCorpoChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property SubTitulo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SubTitulo
        {
            get
            {
                return this._SubTitulo;
            }
            set
            {
                this.OnSubTituloChanging(value);
                this.ReportPropertyChanging("SubTitulo");
                this._SubTitulo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SubTitulo");
                this.OnSubTituloChanged();
            }
        }
        private string _SubTitulo;
        partial void OnSubTituloChanging(string value);
        partial void OnSubTituloChanged();
        /// <summary>
        /// There are no comments for Property Titulo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo
        {
            get
            {
                return this._Titulo;
            }
            set
            {
                this.OnTituloChanging(value);
                this.ReportPropertyChanging("Titulo");
                this._Titulo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Titulo");
                this.OnTituloChanged();
            }
        }
        private string _Titulo;
        partial void OnTituloChanging(string value);
        partial void OnTituloChanged();
    }
    /// <summary>
    /// There are no comments for freddacaixaModel.Proposta in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="freddacaixaModel", Name="Proposta")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Proposta : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Proposta object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static Proposta CreateProposta(int id)
        {
            Proposta proposta = new Proposta();
            proposta.ID = id;
            return proposta;
        }
        /// <summary>
        /// There are no comments for Property Corpo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Corpo
        {
            get
            {
                return this._Corpo;
            }
            set
            {
                this.OnCorpoChanging(value);
                this.ReportPropertyChanging("Corpo");
                this._Corpo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Corpo");
                this.OnCorpoChanged();
            }
        }
        private string _Corpo;
        partial void OnCorpoChanging(string value);
        partial void OnCorpoChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property SubTitulo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SubTitulo
        {
            get
            {
                return this._SubTitulo;
            }
            set
            {
                this.OnSubTituloChanging(value);
                this.ReportPropertyChanging("SubTitulo");
                this._SubTitulo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SubTitulo");
                this.OnSubTituloChanged();
            }
        }
        private string _SubTitulo;
        partial void OnSubTituloChanging(string value);
        partial void OnSubTituloChanged();
        /// <summary>
        /// There are no comments for Property Titulo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo
        {
            get
            {
                return this._Titulo;
            }
            set
            {
                this.OnTituloChanging(value);
                this.ReportPropertyChanging("Titulo");
                this._Titulo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Titulo");
                this.OnTituloChanged();
            }
        }
        private string _Titulo;
        partial void OnTituloChanging(string value);
        partial void OnTituloChanged();
    }
    /// <summary>
    /// There are no comments for freddacaixaModel.Usuario in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="freddacaixaModel", Name="Usuario")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Usuario : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="login">Initial value of Login.</param>
        /// <param name="senha">Initial value of Senha.</param>
        public static Usuario CreateUsuario(int id, string login, string senha)
        {
            Usuario usuario = new Usuario();
            usuario.ID = id;
            usuario.Login = login;
            usuario.Senha = senha;
            return usuario;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Login in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this._Login;
            }
            set
            {
                this.OnLoginChanging(value);
                this.ReportPropertyChanging("Login");
                this._Login = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Login");
                this.OnLoginChanged();
            }
        }
        private string _Login;
        partial void OnLoginChanging(string value);
        partial void OnLoginChanged();
        /// <summary>
        /// There are no comments for Property Senha in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha
        {
            get
            {
                return this._Senha;
            }
            set
            {
                this.OnSenhaChanging(value);
                this.ReportPropertyChanging("Senha");
                this._Senha = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Senha");
                this.OnSenhaChanged();
            }
        }
        private string _Senha;
        partial void OnSenhaChanging(string value);
        partial void OnSenhaChanged();
    }
}
