//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FredDaCaixaModel", "fk_Foto_Galeria", "galeria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RegraNegocio.ModuloBasico.Galeria), "foto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RegraNegocio.ModuloBasico.Foto), true)]

#endregion

namespace RegraNegocio.ModuloBasico
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FredDaCaixaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FredDaCaixaEntities object using the connection string found in the 'FredDaCaixaEntities' section of the application configuration file.
        /// </summary>
        public FredDaCaixaEntities() : base("name=FredDaCaixaEntities", "FredDaCaixaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FredDaCaixaEntities object.
        /// </summary>
        public FredDaCaixaEntities(string connectionString) : base(connectionString, "FredDaCaixaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FredDaCaixaEntities object.
        /// </summary>
        public FredDaCaixaEntities(EntityConnection connection) : base(connection, "FredDaCaixaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Foto> Foto
        {
            get
            {
                if ((_Foto == null))
                {
                    _Foto = base.CreateObjectSet<Foto>("Foto");
                }
                return _Foto;
            }
        }
        private ObjectSet<Foto> _Foto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Galeria> Galeria
        {
            get
            {
                if ((_Galeria == null))
                {
                    _Galeria = base.CreateObjectSet<Galeria>("Galeria");
                }
                return _Galeria;
            }
        }
        private ObjectSet<Galeria> _Galeria;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Index> Index
        {
            get
            {
                if ((_Index == null))
                {
                    _Index = base.CreateObjectSet<Index>("Index");
                }
                return _Index;
            }
        }
        private ObjectSet<Index> _Index;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Proposta> Proposta
        {
            get
            {
                if ((_Proposta == null))
                {
                    _Proposta = base.CreateObjectSet<Proposta>("Proposta");
                }
                return _Proposta;
            }
        }
        private ObjectSet<Proposta> _Proposta;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Partido> Partido
        {
            get
            {
                if ((_Partido == null))
                {
                    _Partido = base.CreateObjectSet<Partido>("Partido");
                }
                return _Partido;
            }
        }
        private ObjectSet<Partido> _Partido;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Perfil> Perfil
        {
            get
            {
                if ((_Perfil == null))
                {
                    _Perfil = base.CreateObjectSet<Perfil>("Perfil");
                }
                return _Perfil;
            }
        }
        private ObjectSet<Perfil> _Perfil;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Lider> Lider
        {
            get
            {
                if ((_Lider == null))
                {
                    _Lider = base.CreateObjectSet<Lider>("Lider");
                }
                return _Lider;
            }
        }
        private ObjectSet<Lider> _Lider;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Video> Video
        {
            get
            {
                if ((_Video == null))
                {
                    _Video = base.CreateObjectSet<Video>("Video");
                }
                return _Video;
            }
        }
        private ObjectSet<Video> _Video;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Localidades> Localidades
        {
            get
            {
                if ((_Localidades == null))
                {
                    _Localidades = base.CreateObjectSet<Localidades>("Localidades");
                }
                return _Localidades;
            }
        }
        private ObjectSet<Localidades> _Localidades;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Foto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoto(Foto foto)
        {
            base.AddObject("Foto", foto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Galeria EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGaleria(Galeria galeria)
        {
            base.AddObject("Galeria", galeria);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Index EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIndex(Index index)
        {
            base.AddObject("Index", index);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Proposta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProposta(Proposta proposta)
        {
            base.AddObject("Proposta", proposta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Partido EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPartido(Partido partido)
        {
            base.AddObject("Partido", partido);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Perfil EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPerfil(Perfil perfil)
        {
            base.AddObject("Perfil", perfil);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Lider EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLider(Lider lider)
        {
            base.AddObject("Lider", lider);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Video EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVideo(Video video)
        {
            base.AddObject("Video", video);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Localidades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLocalidades(Localidades localidades)
        {
            base.AddObject("Localidades", localidades);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Foto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Foto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Foto object.
        /// </summary>
        /// <param name="galeriaID">Initial value of the GaleriaID property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static Foto CreateFoto(global::System.Int32 galeriaID, global::System.Int32 id)
        {
            Foto foto = new Foto();
            foto.GaleriaID = galeriaID;
            foto.ID = id;
            return foto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GaleriaID
        {
            get
            {
                return _GaleriaID;
            }
            set
            {
                OnGaleriaIDChanging(value);
                ReportPropertyChanging("GaleriaID");
                _GaleriaID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GaleriaID");
                OnGaleriaIDChanged();
            }
        }
        private global::System.Int32 _GaleriaID;
        partial void OnGaleriaIDChanging(global::System.Int32 value);
        partial void OnGaleriaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagemUrl
        {
            get
            {
                return _ImagemUrl;
            }
            set
            {
                OnImagemUrlChanging(value);
                ReportPropertyChanging("ImagemUrl");
                _ImagemUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagemUrl");
                OnImagemUrlChanged();
            }
        }
        private global::System.String _ImagemUrl;
        partial void OnImagemUrlChanging(global::System.String value);
        partial void OnImagemUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Legenda
        {
            get
            {
                return _Legenda;
            }
            set
            {
                OnLegendaChanging(value);
                ReportPropertyChanging("Legenda");
                _Legenda = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Legenda");
                OnLegendaChanged();
            }
        }
        private global::System.String _Legenda;
        partial void OnLegendaChanging(global::System.String value);
        partial void OnLegendaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FredDaCaixaModel", "fk_Foto_Galeria", "galeria")]
        public Galeria galeria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galeria>("FredDaCaixaModel.fk_Foto_Galeria", "galeria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galeria>("FredDaCaixaModel.fk_Foto_Galeria", "galeria").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Galeria> galeriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galeria>("FredDaCaixaModel.fk_Foto_Galeria", "galeria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Galeria>("FredDaCaixaModel.fk_Foto_Galeria", "galeria", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Galeria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Galeria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Galeria object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Galeria CreateGaleria(global::System.Int32 id)
        {
            Galeria galeria = new Galeria();
            galeria.ID = id;
            return galeria;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagemUrl
        {
            get
            {
                return _ImagemUrl;
            }
            set
            {
                OnImagemUrlChanging(value);
                ReportPropertyChanging("ImagemUrl");
                _ImagemUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagemUrl");
                OnImagemUrlChanged();
            }
        }
        private global::System.String _ImagemUrl;
        partial void OnImagemUrlChanging(global::System.String value);
        partial void OnImagemUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Legenda
        {
            get
            {
                return _Legenda;
            }
            set
            {
                OnLegendaChanging(value);
                ReportPropertyChanging("Legenda");
                _Legenda = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Legenda");
                OnLegendaChanged();
            }
        }
        private global::System.String _Legenda;
        partial void OnLegendaChanging(global::System.String value);
        partial void OnLegendaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FredDaCaixaModel", "fk_Foto_Galeria", "foto")]
        public EntityCollection<Foto> foto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Foto>("FredDaCaixaModel.fk_Foto_Galeria", "foto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Foto>("FredDaCaixaModel.fk_Foto_Galeria", "foto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Index")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Index : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Index object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Index CreateIndex(global::System.Int32 id)
        {
            Index index = new Index();
            index.ID = id;
            return index;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Corpo
        {
            get
            {
                return _Corpo;
            }
            set
            {
                OnCorpoChanging(value);
                ReportPropertyChanging("Corpo");
                _Corpo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Corpo");
                OnCorpoChanged();
            }
        }
        private global::System.String _Corpo;
        partial void OnCorpoChanging(global::System.String value);
        partial void OnCorpoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubTitulo
        {
            get
            {
                return _SubTitulo;
            }
            set
            {
                OnSubTituloChanging(value);
                ReportPropertyChanging("SubTitulo");
                _SubTitulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubTitulo");
                OnSubTituloChanged();
            }
        }
        private global::System.String _SubTitulo;
        partial void OnSubTituloChanging(global::System.String value);
        partial void OnSubTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Lider")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Lider : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Lider object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Lider CreateLider(global::System.Int32 id)
        {
            Lider lider = new Lider();
            lider.ID = id;
            return lider;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bairro
        {
            get
            {
                return _Bairro;
            }
            set
            {
                OnBairroChanging(value);
                ReportPropertyChanging("Bairro");
                _Bairro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bairro");
                OnBairroChanged();
            }
        }
        private global::System.String _Bairro;
        partial void OnBairroChanging(global::System.String value);
        partial void OnBairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cep
        {
            get
            {
                return _Cep;
            }
            set
            {
                OnCepChanging(value);
                ReportPropertyChanging("Cep");
                _Cep = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cep");
                OnCepChanged();
            }
        }
        private global::System.String _Cep;
        partial void OnCepChanging(global::System.String value);
        partial void OnCepChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cidade
        {
            get
            {
                return _Cidade;
            }
            set
            {
                OnCidadeChanging(value);
                ReportPropertyChanging("Cidade");
                _Cidade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cidade");
                OnCidadeChanged();
            }
        }
        private global::System.String _Cidade;
        partial void OnCidadeChanging(global::System.String value);
        partial void OnCidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Complemento
        {
            get
            {
                return _Complemento;
            }
            set
            {
                OnComplementoChanging(value);
                ReportPropertyChanging("Complemento");
                _Complemento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Complemento");
                OnComplementoChanged();
            }
        }
        private global::System.String _Complemento;
        partial void OnComplementoChanging(global::System.String value);
        partial void OnComplementoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cpf
        {
            get
            {
                return _Cpf;
            }
            set
            {
                OnCpfChanging(value);
                ReportPropertyChanging("Cpf");
                _Cpf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cpf");
                OnCpfChanged();
            }
        }
        private global::System.String _Cpf;
        partial void OnCpfChanging(global::System.String value);
        partial void OnCpfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Local
        {
            get
            {
                return _Local;
            }
            set
            {
                OnLocalChanging(value);
                ReportPropertyChanging("Local");
                _Local = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Local");
                OnLocalChanged();
            }
        }
        private global::System.String _Local;
        partial void OnLocalChanging(global::System.String value);
        partial void OnLocalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Logradouro
        {
            get
            {
                return _Logradouro;
            }
            set
            {
                OnLogradouroChanging(value);
                ReportPropertyChanging("Logradouro");
                _Logradouro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Logradouro");
                OnLogradouroChanged();
            }
        }
        private global::System.String _Logradouro;
        partial void OnLogradouroChanging(global::System.String value);
        partial void OnLogradouroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.String _Numero;
        partial void OnNumeroChanging(global::System.String value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Obs
        {
            get
            {
                return _Obs;
            }
            set
            {
                OnObsChanging(value);
                ReportPropertyChanging("Obs");
                _Obs = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Obs");
                OnObsChanged();
            }
        }
        private global::System.String _Obs;
        partial void OnObsChanging(global::System.String value);
        partial void OnObsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rg
        {
            get
            {
                return _Rg;
            }
            set
            {
                OnRgChanging(value);
                ReportPropertyChanging("Rg");
                _Rg = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rg");
                OnRgChanged();
            }
        }
        private global::System.String _Rg;
        partial void OnRgChanging(global::System.String value);
        partial void OnRgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone1
        {
            get
            {
                return _Telefone1;
            }
            set
            {
                OnTelefone1Changing(value);
                ReportPropertyChanging("Telefone1");
                _Telefone1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone1");
                OnTelefone1Changed();
            }
        }
        private global::System.String _Telefone1;
        partial void OnTelefone1Changing(global::System.String value);
        partial void OnTelefone1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone2
        {
            get
            {
                return _Telefone2;
            }
            set
            {
                OnTelefone2Changing(value);
                ReportPropertyChanging("Telefone2");
                _Telefone2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone2");
                OnTelefone2Changed();
            }
        }
        private global::System.String _Telefone2;
        partial void OnTelefone2Changing(global::System.String value);
        partial void OnTelefone2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Serie
        {
            get
            {
                return _Serie;
            }
            set
            {
                OnSerieChanging(value);
                ReportPropertyChanging("Serie");
                _Serie = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Serie");
                OnSerieChanged();
            }
        }
        private global::System.String _Serie;
        partial void OnSerieChanging(global::System.String value);
        partial void OnSerieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zona
        {
            get
            {
                return _Zona;
            }
            set
            {
                OnZonaChanging(value);
                ReportPropertyChanging("Zona");
                _Zona = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zona");
                OnZonaChanged();
            }
        }
        private global::System.String _Zona;
        partial void OnZonaChanging(global::System.String value);
        partial void OnZonaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Localidades")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Localidades : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Localidades object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Localidades CreateLocalidades(global::System.Int32 id)
        {
            Localidades localidades = new Localidades();
            localidades.ID = id;
            return localidades;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Partido")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Partido : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Partido object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Partido CreatePartido(global::System.Int32 id)
        {
            Partido partido = new Partido();
            partido.ID = id;
            return partido;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Corpo
        {
            get
            {
                return _Corpo;
            }
            set
            {
                OnCorpoChanging(value);
                ReportPropertyChanging("Corpo");
                _Corpo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Corpo");
                OnCorpoChanged();
            }
        }
        private global::System.String _Corpo;
        partial void OnCorpoChanging(global::System.String value);
        partial void OnCorpoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubTitulo
        {
            get
            {
                return _SubTitulo;
            }
            set
            {
                OnSubTituloChanging(value);
                ReportPropertyChanging("SubTitulo");
                _SubTitulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubTitulo");
                OnSubTituloChanged();
            }
        }
        private global::System.String _SubTitulo;
        partial void OnSubTituloChanging(global::System.String value);
        partial void OnSubTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Perfil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Perfil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Perfil object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Perfil CreatePerfil(global::System.Int32 id)
        {
            Perfil perfil = new Perfil();
            perfil.ID = id;
            return perfil;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Corpo
        {
            get
            {
                return _Corpo;
            }
            set
            {
                OnCorpoChanging(value);
                ReportPropertyChanging("Corpo");
                _Corpo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Corpo");
                OnCorpoChanged();
            }
        }
        private global::System.String _Corpo;
        partial void OnCorpoChanging(global::System.String value);
        partial void OnCorpoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubTitulo
        {
            get
            {
                return _SubTitulo;
            }
            set
            {
                OnSubTituloChanging(value);
                ReportPropertyChanging("SubTitulo");
                _SubTitulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubTitulo");
                OnSubTituloChanged();
            }
        }
        private global::System.String _SubTitulo;
        partial void OnSubTituloChanging(global::System.String value);
        partial void OnSubTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Proposta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Proposta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Proposta object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Proposta CreateProposta(global::System.Int32 id)
        {
            Proposta proposta = new Proposta();
            proposta.ID = id;
            return proposta;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Corpo
        {
            get
            {
                return _Corpo;
            }
            set
            {
                OnCorpoChanging(value);
                ReportPropertyChanging("Corpo");
                _Corpo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Corpo");
                OnCorpoChanged();
            }
        }
        private global::System.String _Corpo;
        partial void OnCorpoChanging(global::System.String value);
        partial void OnCorpoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubTitulo
        {
            get
            {
                return _SubTitulo;
            }
            set
            {
                OnSubTituloChanging(value);
                ReportPropertyChanging("SubTitulo");
                _SubTitulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubTitulo");
                OnSubTituloChanged();
            }
        }
        private global::System.String _SubTitulo;
        partial void OnSubTituloChanging(global::System.String value);
        partial void OnSubTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String login, global::System.String senha)
        {
            Usuario usuario = new Usuario();
            usuario.ID = id;
            usuario.Login = login;
            usuario.Senha = senha;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Video")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Video : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Video object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Video CreateVideo(global::System.Int32 id)
        {
            Video video = new Video();
            video.ID = id;
            return video;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Corpo
        {
            get
            {
                return _Corpo;
            }
            set
            {
                OnCorpoChanging(value);
                ReportPropertyChanging("Corpo");
                _Corpo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Corpo");
                OnCorpoChanged();
            }
        }
        private global::System.String _Corpo;
        partial void OnCorpoChanging(global::System.String value);
        partial void OnCorpoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubTitulo
        {
            get
            {
                return _SubTitulo;
            }
            set
            {
                OnSubTituloChanging(value);
                ReportPropertyChanging("SubTitulo");
                _SubTitulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubTitulo");
                OnSubTituloChanged();
            }
        }
        private global::System.String _SubTitulo;
        partial void OnSubTituloChanging(global::System.String value);
        partial void OnSubTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();

        #endregion
    
    }

    #endregion
    
}
