//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FredDaCaixaModel", "fk_Foto_Galeria", "galeria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RegraNegocio.ModuloBasico.Galeria), "foto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RegraNegocio.ModuloBasico.Foto), true)]

#endregion

namespace RegraNegocio.ModuloBasico
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FredDaCaixaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FredDaCaixaEntities object using the connection string found in the 'FredDaCaixaEntities' section of the application configuration file.
        /// </summary>
        public FredDaCaixaEntities() : base("name=FredDaCaixaEntities", "FredDaCaixaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FredDaCaixaEntities object.
        /// </summary>
        public FredDaCaixaEntities(string connectionString) : base(connectionString, "FredDaCaixaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FredDaCaixaEntities object.
        /// </summary>
        public FredDaCaixaEntities(EntityConnection connection) : base(connection, "FredDaCaixaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Foto> fotoes
        {
            get
            {
                if ((_fotoes == null))
                {
                    _fotoes = base.CreateObjectSet<Foto>("fotoes");
                }
                return _fotoes;
            }
        }
        private ObjectSet<Foto> _fotoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Galeria> galerias
        {
            get
            {
                if ((_galerias == null))
                {
                    _galerias = base.CreateObjectSet<Galeria>("galerias");
                }
                return _galerias;
            }
        }
        private ObjectSet<Galeria> _galerias;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Index> indices
        {
            get
            {
                if ((_indices == null))
                {
                    _indices = base.CreateObjectSet<Index>("indices");
                }
                return _indices;
            }
        }
        private ObjectSet<Index> _indices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Proposta> propostas
        {
            get
            {
                if ((_propostas == null))
                {
                    _propostas = base.CreateObjectSet<Proposta>("propostas");
                }
                return _propostas;
            }
        }
        private ObjectSet<Proposta> _propostas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<Usuario>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<Usuario> _usuarios;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the fotoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofotoes(Foto foto)
        {
            base.AddObject("fotoes", foto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the galerias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogalerias(Galeria galeria)
        {
            base.AddObject("galerias", galeria);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the indices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToindices(Index index)
        {
            base.AddObject("indices", index);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the propostas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopropostas(Proposta proposta)
        {
            base.AddObject("propostas", proposta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuarios(Usuario usuario)
        {
            base.AddObject("usuarios", usuario);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Foto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Foto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Foto object.
        /// </summary>
        /// <param name="galeriaID">Initial value of the GaleriaID property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static Foto CreateFoto(global::System.Int32 galeriaID, global::System.Int32 id)
        {
            Foto foto = new Foto();
            foto.GaleriaID = galeriaID;
            foto.ID = id;
            return foto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GaleriaID
        {
            get
            {
                return _GaleriaID;
            }
            set
            {
                OnGaleriaIDChanging(value);
                ReportPropertyChanging("GaleriaID");
                _GaleriaID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GaleriaID");
                OnGaleriaIDChanged();
            }
        }
        private global::System.Int32 _GaleriaID;
        partial void OnGaleriaIDChanging(global::System.Int32 value);
        partial void OnGaleriaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagemUrl
        {
            get
            {
                return _ImagemUrl;
            }
            set
            {
                OnImagemUrlChanging(value);
                ReportPropertyChanging("ImagemUrl");
                _ImagemUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagemUrl");
                OnImagemUrlChanged();
            }
        }
        private global::System.String _ImagemUrl;
        partial void OnImagemUrlChanging(global::System.String value);
        partial void OnImagemUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Legenda
        {
            get
            {
                return _Legenda;
            }
            set
            {
                OnLegendaChanging(value);
                ReportPropertyChanging("Legenda");
                _Legenda = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Legenda");
                OnLegendaChanged();
            }
        }
        private global::System.String _Legenda;
        partial void OnLegendaChanging(global::System.String value);
        partial void OnLegendaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FredDaCaixaModel", "fk_Foto_Galeria", "galeria")]
        public Galeria galeria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galeria>("FredDaCaixaModel.fk_Foto_Galeria", "galeria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galeria>("FredDaCaixaModel.fk_Foto_Galeria", "galeria").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Galeria> galeriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Galeria>("FredDaCaixaModel.fk_Foto_Galeria", "galeria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Galeria>("FredDaCaixaModel.fk_Foto_Galeria", "galeria", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Galeria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Galeria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Galeria object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Galeria CreateGaleria(global::System.Int32 id)
        {
            Galeria galeria = new Galeria();
            galeria.ID = id;
            return galeria;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagemUrl
        {
            get
            {
                return _ImagemUrl;
            }
            set
            {
                OnImagemUrlChanging(value);
                ReportPropertyChanging("ImagemUrl");
                _ImagemUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagemUrl");
                OnImagemUrlChanged();
            }
        }
        private global::System.String _ImagemUrl;
        partial void OnImagemUrlChanging(global::System.String value);
        partial void OnImagemUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Legenda
        {
            get
            {
                return _Legenda;
            }
            set
            {
                OnLegendaChanging(value);
                ReportPropertyChanging("Legenda");
                _Legenda = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Legenda");
                OnLegendaChanged();
            }
        }
        private global::System.String _Legenda;
        partial void OnLegendaChanging(global::System.String value);
        partial void OnLegendaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FredDaCaixaModel", "fk_Foto_Galeria", "foto")]
        public EntityCollection<Foto> fotoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Foto>("FredDaCaixaModel.fk_Foto_Galeria", "foto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Foto>("FredDaCaixaModel.fk_Foto_Galeria", "foto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Index")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Index : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Index object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Index CreateIndex(global::System.Int32 id)
        {
            Index index = new Index();
            index.ID = id;
            return index;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Corpo
        {
            get
            {
                return _Corpo;
            }
            set
            {
                OnCorpoChanging(value);
                ReportPropertyChanging("Corpo");
                _Corpo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Corpo");
                OnCorpoChanged();
            }
        }
        private global::System.String _Corpo;
        partial void OnCorpoChanging(global::System.String value);
        partial void OnCorpoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubTitulo
        {
            get
            {
                return _SubTitulo;
            }
            set
            {
                OnSubTituloChanging(value);
                ReportPropertyChanging("SubTitulo");
                _SubTitulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubTitulo");
                OnSubTituloChanged();
            }
        }
        private global::System.String _SubTitulo;
        partial void OnSubTituloChanging(global::System.String value);
        partial void OnSubTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Proposta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Proposta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Proposta object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Proposta CreateProposta(global::System.Int32 id)
        {
            Proposta proposta = new Proposta();
            proposta.ID = id;
            return proposta;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Corpo
        {
            get
            {
                return _Corpo;
            }
            set
            {
                OnCorpoChanging(value);
                ReportPropertyChanging("Corpo");
                _Corpo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Corpo");
                OnCorpoChanged();
            }
        }
        private global::System.String _Corpo;
        partial void OnCorpoChanging(global::System.String value);
        partial void OnCorpoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubTitulo
        {
            get
            {
                return _SubTitulo;
            }
            set
            {
                OnSubTituloChanging(value);
                ReportPropertyChanging("SubTitulo");
                _SubTitulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubTitulo");
                OnSubTituloChanged();
            }
        }
        private global::System.String _SubTitulo;
        partial void OnSubTituloChanging(global::System.String value);
        partial void OnSubTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FredDaCaixaModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String login, global::System.String senha)
        {
            Usuario usuario = new Usuario();
            usuario.ID = id;
            usuario.Login = login;
            usuario.Senha = senha;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();

        #endregion
    
    }

    #endregion
    
}
